### ISSUE TITLE
Error about Dataset

### ISSUE THREAD

**Issue by TianhangWang** [GT-RIPL/MultiAgentPerception#2]
Sorry to bother you! Here I unziped "airsim-mrms-noise-data.zip", then I run the model, it throw out the error below:

```
Loaded: selection label.
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    t_loader = data_loader(
  File "G:\TWang\MultiAgentPerception-master\ptsemseg\loader\airsim_loader.py", line 258, in __init__
    raise Exception(
Exception: No files for split=[train] found in dataset/airsim-mrms-noise-data
```

Actually, I split the dataset into the form, according to 
![屏幕截图 2021-11-18 104736](https://user-images.githubusercontent.com/42128414/142342544-972b64de-432e-4690-9fed-56224a89d151.png)

Could you show me how you construct your dataset form? Or there lack the code of preprocess dataset to generate the split form?

**Comment by TianhangWang** [comment]
Ok, I run the code in windows instead of Linux, so if you want to run in windows you should replace the code of "airsim_loader.py" about 237 line `file_list = sorted(glob.glob(os.path.join(root, 'scene', 'async_rotate_fog_000_clear',subdir,self.cam_pos[0],'*.png'),recursive=True))` to `file_list = sorted(glob.glob((root + '/scene/' + 'async_rotate_fog_000_clear/' + subdir + '/' + self.cam_pos[0] + '/' + '*.png'),recursive=True))` and add `file_path = file_path.replace("\\", '/')` in line 240. 
The code will run normally.
